apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nous-intel
  namespace: security
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # storageClassName: <your-storage-class>  # omit to use cluster default
