apiVersion: v1
kind: Secret
metadata:
  name: falco-talon-config
  namespace: falco
type: Opaque
stringData:
  config.yaml: |
    listen_address: 0.0.0.0
    listen_port: 2803
    rules_file: /etc/falco-talon/rules.yaml
