"""
attck.py — MITRE ATT&CK enrichment for PanOps assembler LLM prompts.

Lazily loads two files from the intel rules volume:
  /rules/cti/attack-enterprise.json  — ATT&CK STIX bundle (downloaded by intel-updater)
  /rules/cti/sigma-attack-index.json — sigma rule UUID → [T-IDs] (generated by intel-updater)

Fail-open: if either file is absent (intel bundle not yet applied to the pod's rules
volume), all enrichment returns empty strings without raising.
"""
import json
import os
from pathlib import Path

_RULES_BASE  = Path(os.getenv("RULES_DIR", "/rules"))
_STIX_PATH   = Path(os.getenv("ATTCK_STIX_PATH",  str(_RULES_BASE / "cti/attack-enterprise.json")))
_INDEX_PATH  = Path(os.getenv("SIGMA_INDEX_PATH",  str(_RULES_BASE / "cti/sigma-attack-index.json")))

_TECH_DB:   dict = {}   # T1234 → {id, name, tactic, platforms, summary}
_SIGMA_IDX: dict = {}   # sigma_uuid → [T1234, ...]
_LOADED = False


def _load():
    global _TECH_DB, _SIGMA_IDX, _LOADED
    if _LOADED:
        return
    _LOADED = True

    if _STIX_PATH.exists():
        try:
            data = json.loads(_STIX_PATH.read_bytes())
            for obj in data.get("objects", []):
                if obj.get("type") != "attack-pattern":
                    continue
                for ref in obj.get("external_references", []):
                    if ref.get("source_name") != "mitre-attack":
                        continue
                    aid = (ref.get("external_id") or "").upper()
                    if not aid:
                        continue
                    tactics = [
                        p["phase_name"].replace("-", " ").title()
                        for p in obj.get("kill_chain_phases", [])
                        if p.get("kill_chain_name") == "mitre-attack"
                    ]
                    desc = obj.get("description") or ""
                    summary = desc.split(". ")[0][:200] if desc else ""
                    _TECH_DB[aid] = {
                        "id":        ref["external_id"],
                        "name":      obj.get("name", ""),
                        "tactic":    ", ".join(tactics) or "unknown",
                        "platforms": obj.get("x_mitre_platforms", []),
                        "summary":   summary,
                    }
        except Exception:
            pass

    if _INDEX_PATH.exists():
        try:
            _SIGMA_IDX.update(json.loads(_INDEX_PATH.read_bytes()))
        except Exception:
            pass


def lookup(attack_id: str) -> dict | None:
    """Return technique metadata dict for a given ATT&CK ID, or None."""
    _load()
    return _TECH_DB.get((attack_id or "").upper())


def enrich_sigma_ids(sigma_rule_ids: list) -> str:
    """
    Given a list of Sigma rule UUIDs (from panops.happenings.sigma_rule_ids), return a
    formatted ATT&CK context block for injection into the LLM prompt.

    Lookup chain:  sigma UUID → sigma-attack-index → T-IDs → STIX technique metadata.
    Returns "" if the intel bundle is not loaded or no technique mappings exist.
    """
    if not sigma_rule_ids:
        return ""
    _load()
    if not _SIGMA_IDX or not _TECH_DB:
        return ""

    seen: set = set()
    lines: list = []
    for rule_uuid in sigma_rule_ids:
        for aid in _SIGMA_IDX.get(str(rule_uuid), []):
            if aid in seen:
                continue
            seen.add(aid)
            tech = _TECH_DB.get(aid.upper())
            if not tech:
                continue
            line = f"  {tech['id']} {tech['name']} [{tech['tactic']}]"
            if tech.get("summary"):
                line += f" — {tech['summary']}"
            lines.append(line)

    if not lines:
        return ""
    return "ATT&CK Techniques (from Sigma matches):\n" + "\n".join(lines)
