apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Secrets 'grafana-admin-credentials', 'grafana-smtp-credentials' (optional),
# 'grafana-oidc-credentials' (optional, for SSO)
# in namespace 'observability' must exist before applying.
# Created by: python3 deploy/configure.py
resources:
  - grafana-serviceaccount.yaml
  - grafana-ini-cm.yaml
  - grafana-datasources-cm.yaml
  - grafana-dashboard-provisioner-cm.yaml
  - grafana-alerting-rules-cm.yaml
  - grafana-alerting-contactpoints-cm.yaml
  - grafana-service.yaml
  - grafana-deployment.yaml
  - grafana-httproute.yaml
