apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-config
  namespace: observability
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        prober: http
        http:
          preferred_ip_protocol: ip4
          valid_status_codes: [200, 201, 202, 204]

      http_401_ok:
        prober: http
        http:
          preferred_ip_protocol: ip4
          valid_status_codes: [200, 401, 403]

      http_gateway:
        prober: http
        http:
          preferred_ip_protocol: ip4
          valid_status_codes: [200, 201, 202, 204, 301, 302, 404]

      tcp_connect:
        prober: tcp
