apiVersion: v1
kind: Secret
metadata:
  name: falco-talon-config
  namespace: security
  labels:
    app.kubernetes.io/part-of: falco-talon
    app.kubernetes.io/name: falco-talon
stringData:
  config.yaml: |
    listen_address: 0.0.0.0
    listen_port: 2803
    watch_rules: true
    print_all_events: false

    deduplication:
      leader_election: false
      time_window_seconds: 5

    default_notifiers:
      - k8sevents
      - loki

    notifiers:
      loki:
        url: http://gigapipe.observability.svc.cluster.local:3100
