apiVersion: v1
kind: Service
metadata:
  name: gigapipe
  namespace: observability
  labels:
    app: gigapipe
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3100
    targetPort: http
    protocol: TCP
  selector:
    app: gigapipe
